myfirstprj/myfirstprj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('namespace/', include('namespace.urls')),
]

""" 
    127.0.0.1:8000/polls/main
                   1차        2차
    url은 2개로 나뉜다.
    1차 url :어플리케이션 선택 , 2차 url : 어떤 기능을 호출할지!
    include : polls내부의 urls.py 지칭!
"""

myfirstprj/namespace/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from namespace import views

app_name="namespace"

urlpatterns = [
    path('main', views.index, name="index"),
    path('lotto', views.lotto, name="lotto"),
    path('naver', views.naver, name="naver"),
    path('daum', views.daum, name="daum"),
    path('lottomove', views.lottomove, name="lottomove"),
]
# 위에서 아래로 왼쪽에서 오른쪽으로 스캔을 하기 때문에 polls/test에서 main페이지로
# 넘어갈 때 namespace의 main으로 이동함.

myfirstprj/polls/urls.py
from django.urls import path
from . import views

# app_name 변수는 주소에 라벨링을 합니다.
app_name="polls"

urlpatterns = [
        path('main', views.index, name='index'),
        path('test', views.test, name = 'test'),
        path('get', views.get, name ='get'),
        path('getform', views.getform, name = 'getform'),
        path('name', views.get_name, name = 'name'),
        path('nameform', views.nameform, name = 'nameform'),
        path('<int:temp>/ctof', views.temp),
        path('<int:height>/<int:weight>/bmi', views.bmi),
        path('<int:number>/content', views.get_number),
        # int가 들어왔을 때 number라는 변수에 저장
        # number라는 변수는 get_number라는 함수로 전달
        # 127.0.0.1:8000/polls/50
        #                         number
        path('<int:age>/check', views.get_adult_result),
        path('<int:num1>/<int:num2>/two', views.get_two),
        path('<str:name>/name', views.get_name_2),
        path('<str:money1>/<str:money2>/exchange', views.money),
        path('qtest', views.qtest),
        path('<int:price>/price', views.bus_price),
        path('<int:id>', views.detail, name='detail'),
        path('<int:question_id>/results/', views.results, name='results'),
        path('<int:question_id>/vote/', views.vote, name='vote'),
        
    ]
# http://www.127.0.0.1:8080/main

myfirstprj/namespace/models.py
from django.db import models

# Create your models here.

myfirstprj/polls/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    # 질문 내용, charField : 문자 저장. 한글자 한글자 씩 저장, 최대 200글자
    pub_date = models.DateTimeField('date published')
    # 질문 한 날짜, date published : 나중에
    
    def __str__(self):
        return str(self.pk) + ". " + self.question_text + " " + str(self.pub_date)[:10]
    # __str__은 노출 되는 정보를 뭘로 만들건지를 정하는 것!
    # 여기서는 question_text를 노출 되게 만듬
    # 문자열로 출력
    
    
class Choice(models.Model): # 질문에 대한 항목
    question = models.ForeignKey(Question,
                                 on_delete=models.CASCADE)
    # Question에 Choice를 넣어버리면 공간 낭비
    # Question은 하나씩만 저장하면 되지만 Choice는 여러개이므로 중복을 해야함.
    # 그러므로 Choice에서 FK를 사용하여 질문하나에 여러 답변을 사용
    choice_text = models.CharField(max_length=200)
    # 선택 항목
    votes = models.IntegerField(default=0)
    # 투표, 기본 속성으로 0 부여 
    
    def __str__(self):
        return str(self.question) + "|" + str(self.choice_text)
    
# PK는 자동으로 하나씩 들어감! 중복된 값 못가짐. 2번없어진다고 2번 안채워짐.

myfirstprj/namespace/views.py
from django.shortcuts import render
import random
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse

def index(request):
    print(reverse('namespace:lotto'))
    print(reverse('polls:test'))
    print(reverse('polls:results', args=(10,)))
    return render(request, 'namespace/index.html')

def lotto(request):
    lottonum = []
    while len(lottonum) != 6:
        lotto = random.randint(1, 45)
        if lotto not in lottonum:
            lottonum.append(lotto)
    lottonum.sort()
    while lotto in lottonum:
        lotto = random.randint(1, 45)
    print(lottonum)
    print("2등 번호는 %d 입니다" % lotto)
    return render(request, 'namespace/lotto.html',
                  {'lottonum':lottonum,'lotto':lotto})
    
def naver(request):
    print("네이버 페이지로 강제 링크됩니다.")
    return HttpResponseRedirect('http://www.naver.com')

def daum(request):
    print("daum 사이트로 이동하셨습니다.")
    return HttpResponseRedirect('http://www.daum.net')

def lottomove(request):
    print("lotto 페이지로 이동하셨습니다.")
    return HttpResponseRedirect('lotto')


myfirstprj/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from polls.models import Question
from django.urls.base import reverse
from django.http.response import HttpResponseRedirect

def index(request):
    latest_question_list = Question.objects.order_by(
        '-pub_date')
    return render(request, 'polls/index.html',
                  {"latest_question_list":latest_question_list})
 
def test(request):
    return render(request, 'polls/test.html')

def getform(request):
    return render(request, 'polls/getform.html')

def get(request):
    str1 = request.POST.get('str1')
    str2 = request.POST.get('str2')
    return render(request, 'polls/get.html',
                  {"str1":str1, "str2":str2})
    # str1이라는 이름의 str1자료를 보내주고 ""안에 있는게 넘기는거
    
def nameform(request):
    return render(request, 'polls/nameform.html')
    
def get_name(request):
    name = request.POST.get('name')
    return render(request, 'polls/get_name.html',
                  {"name":name})

def temp(request, temp):
    stemp = temp
    htemp = 1.8 * temp + 32 # htemp : 화씨, stemp : 섭씨
    return render(request, 'polls/ctof.html',
                  {"stemp":stemp, "htemp":htemp})
    # HttpResponse() 괄호안에는 str값만 들어감.
    
def bmi(request, height, weight):
    height = height / 100
    bmi = weight / (height * height)
    return render(request, 'polls/bmi.html',
                  {"height":height, "weight":weight, 
                   "bmi":round(bmi,3)})
    #round( , 3) 소수점 3자리까지 반올림!
    
def get_number(request, number):
    return HttpResponse('<h1>테스트 중입니다.' + 
                        str(number) + '</h1>')
    
def get_adult_result(request, age):
    return render(request, 'polls/adult_check.html',
                      {"age":age})
    
def get_two(request, num1, num2):
    return HttpResponse(str(num1) + " / " + str(num2))
    
def get_name_2(request, name):
    return HttpResponse("당신의 이름은? " + name)
    
def money(request, money1, money2):
    money1 = float(money1)
    money2 = float(money2)
    money2 = money2/170.20
    return HttpResponse("원화 : " + str(money1) + ", " +
                        "위안화 : " + str(round(money2, 3)))
    
def qtest(request):
    question_all = Question.objects.order_by('-pk')
    return render(request, 'polls/question_test.html',
           {"question_all":question_all})

def bus_price(request, price):
    return render(request, 'polls/price.html',
                  {"price":price})
    
def detail(request, id):
    # .get(조건)은 결과가 무조건 1개만 나올 때 쓸 수 있습니다.
    question = get_object_or_404(Question, pk=id)
    return render(request, 'polls/detail.html',
                  {'question':question})
    
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # 1~6개의 질문을 고르는 것
    selected_choice = question.choice_set.get(pk=request.POST['choice'])
    # 그 질문에 해당되는 선택지를 고르는 것
    selected_choice.votes += 1
    selected_choice.save() # DB에 반영
    
    # polls의 results 패턴으로 이동하되 arg를 이용해 투표받은 항목의
    # 질문 번호를 같이 넘겨 주세요.
    return HttpResponseRedirect(
        reverse('polls:results', args = (question_id,)))
    
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html',
                  {'question':question})
    

    
    
    
    
    
    
    

myfirstprj/namespace/templates/namespace/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>namespace 어플리케이션의 메인페이지입니다.</h1>
	<a href = "{% url 'namespace:lotto' %}">lotto링크</a><br>
	<a href = "https://www.naver.com">네이버로 이동</a><br>
	<a href = "{% url 'namespace:naver' %}">네이버로 이동(집계)</a><br>
	<a href = "https://www.daum.net">다음으로 이동</a><br>
	<a href = "{% url 'namespace:daum' %}">다음으로 이동(집계)</a><br>
	<a href = "{% url 'namespace:lottomove' %}">lotto으로 이동(집계)</a><br>
</body>
</html>

myfirstprj/namespace/templates/namespace/lotto.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	
	<h1>1등 번호 : 
	{% for i in lottonum %}
		{{i}}
	{% endfor %}</h1>
		
	<h1>2등 보너스 번호 : {{lotto}}</h1><br>
	<a href = "{% url 'namespace:index' %}">메인페이지</a><br>
	<a href = "{% url 'namespace:lotto' %}">재추첨</a><br>

</body>
</html>

myfirstprj/polls/templates/polls/adult_check.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	{% if age >= 20 %}
		<h1>당신의 나이는 {{age}}세 입니다.</h1>
		<h1>당신은 성인입니다. 주류나 담배를 구매 할 수 있습니다.</h1>
	{% else %}
		<h1>당신의 나이는 {{age}}세 입니다.</h1>
		<h1>당신은 미성년자입니다. 주류나 담배를 구매 할 수 없습니다.</h1>
	{% endif %}
</body>
</html>

myfirstprj/polls/templates/polls/adult_fail.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Child</title>
</head>
<body>
	<h2>미성년입니다<br>
	주류와 담배를 살 수 없습니다.</h2>
</body>
</html>

myfirstprj/polls/templates/polls/adult_ok.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Adult</title>
</head>
<body>
	<h2>성인입니다.<br>
	담배와 주류를 사시겠습니까?</h2>
</body>
</html>

myfirstprj/polls/templates/polls/bmi.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>bmi지수</title>
</head>
<body>
	<h1>키와 몸무게에 따른 bmi지수</h1>
	<table border="1" width="500">
		<tr>
			<td>키</td>
			<td>몸무게</td>
			<td>bmi지수</td>
		</tr>
		<tr>
			<td>{{height}}m</td>
			<td>{{weight}}kg</td>
			<td>{{bmi}}</td>
		</tr>
	</table>
	<a href = "{% url 'polls:index' %}">
	메인으로 돌아가기</a><br>
</body>
</html>

myfirstprj/polls/templates/polls/ctof.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>섭씨 -> 화씨 변환기</h1>
	<table border="1" width="500">
		<tr>
			<td>섭씨</td>
			<td>화씨</td>
		</tr>
		<tr>
			<td>{{stemp}}</td>
			<td>{{htemp}}</td>
		</tr>
	</table>
</body>
</html>

myfirstprj/polls/templates/polls/ctofform.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<!-- form 양식을 전달할 페이지는  -->
	<form method="get">
		<input type="text">
		<input type="submit" value="제출">
	</form>
</body>
</html>

myfirstprj/polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>{{question.question_text}}</h1>
	<!-- 현재 가져온 question과 연계된 choice의 항목 전체 -->
	<form action="{% url 'polls:vote' question.id %}" method="post">
		<!-- post방식으로 보낼때 암호화방식으로 보내게 도와주는 것 -->
		{% csrf_token %} 
		{% for choice in question.choice_set.all %}
			<!-- forloop.counter는 1부터 한 바퀴마다 1씩 자동 증가하는 변수 -->
			<input type="radio" name="choice" 
			id="choice{{forloop.counter}}" value="{{choice.id}}">
			<label for="choice{{forloop.counter}}">
				{{choice.choice_text}}
			</label><br>
		{% endfor %}
			<input type="submit" value="투표하기">
	</form>
</body>
</html>

myfirstprj/polls/templates/polls/get.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
<h1>str1 파라미터의 값 : {{ str1 }}</h1>
<h1>str2 파라미어의 값 : {{ str2 }}</h1>
<!-- str1, str2 : render함수에 넣은 딕셔너리의 키값 -->
</body>
</html>

myfirstprj/polls/templates/polls/get_name.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>사용자의 이름은 : {{name}}입니다.</h1>
</body>
</html>

myfirstprj/polls/templates/polls/nameform.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<!-- form 이란 특정 페이지에 보낼 양식을 작성하는 페이지입니다.
	form 태그를 이용해 작성하며 필수 작성 속성은
	action(목적지의 주소), method(get방식 post방식 선택)입니다. -->
	<!-- get방식은 주소에 전송 정보를 담아서 보냅니다. -->
	<form action="{% url 'polls:name' %}" method="post">
	{% csrf_token %}
		당신의 이름을 적어주세요 :
		<!-- 일반적인 form은 어떤 이름에 자료를 담아서 보낼지
		name 속성으로 지정합니다. -->
		<input type="text" name="name">
		<!-- submit은 제출버튼이며 value속성에 적은 값이
		실제로 버튼에 새겨질 이름이 됩니다. -->
		<input type="submit" value="제출">
	</form>
</body>
</html>

myfirstprj/polls/templates/polls/price.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>나이는 {{price}}입니다.</h1>
	{% if price >= 65 %}
		<h1>노인 요금제입니다.</h1>
	{% elif price >= 20 %}
		<h1>성인 요금제입니다.</h1>
	{% elif price >= 8 %}
		<h1>청소년 요금제입니다.</h1>
	{% elif price >= 0 %}
		<h1>어린이 요금제입니다.</h1>
	{% endif %}
</body>
</html>

myfirstprj/polls/templates/polls/question_test.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<!-- 파이썬 구문을 장고 템플릿 내부에서 사용하고 싶다면 
	{퍼센트 구문 퍼센트} 을 사용한다. -->
	{% for data in question_all %}
		<h1>{{data}}</h1>
	{% endfor %}
	<!-- 파이썬 구문이지만 들여쓰기로 타겟 실행문 범위를 정하지 않을므로
	 끝나는 지점을 같이 작성 해 줘야함 -->
</body>
</html>

myfirstprj/polls/templates/polls/results.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>{{question.question_text}}</h1>
	
	<ul>
		{% for choice in question.choice_set.all %}
			<li>{{ choice.choice_text}} -- {{ choice.votes }} 
			vote{{ choice.votes|pluralize }}</li>
			<!-- pluralize는 0이거나 2이상이면 s가 붙음 -->
		{% endfor %}
	</ul>
	<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>

myfirstprj/polls/templates/polls/test.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>테스트 파일</title>
</head>
<body>
	<h1>render 함수 테스트</h1>
	<div>
		render 함수를 이용하면 이렇게<br>
		html 파일을 완성시켜놓고 연결 할 수 있습니다.
	</div>
	<div>
		이 파일은 HttpResponse 기준으로 한 문자열로 작성해야 하는<br>
		복잡한 코드를 보다 손쉽게 작성할 수 있게 만들어줍니다.
	</div>
	<a href="{% url 'namespace:index' %}">메인링크</a>
	
</body>
</html>
<!-- HttpResponse나 print형식으로 만들기 힘드니까 html에서 만듦 -->